#BDT ---------------------------------------------------------------------------------
# tem_eta_sumw:
#   x_bins: "auto|-2:2"
#   x_title: "#frac{1}{3} #Sigma_{i} #eta_{l_i} "
#   y_title: "Events"
#   use_log_y: False
#   max_y_sf: 1.5
#   divide_by_bin_width: False
#   flow: True

mT_total_tem:
  x_bins: "auto|50:700"
  x_title: "m^{T}_{total} (GeV)"
  y_title: "Events"
  use_log_y: False
  max_y_sf: 1.5
  divide_by_bin_width: False
  flow: True

dr_emu:
  x_bins: "auto|0:5"
  x_title: "#Delta R_{e #mu} (rad)"
  y_title: "Events"
  use_log_y: False
  max_y_sf: 1.5
  divide_by_bin_width: False
  flow: True
  
DNNscore:
  x_bins: "auto|0:1"
  x_title: "DNN score for m_{HNL}="
  y_title: "Events"
  use_log_y: False
  max_y_sf: 1.5
  divide_by_bin_width: False

# pt_sum_tem:
#   x_bins: "auto|60:400"
#   x_title: "#Sigma_{i}^{#tau_{h} e #mu} p_{T}^{i} (GeV)"
#   y_title: "Events"
#   use_log_y: False
#   max_y_sf: 1.5
#   divide_by_bin_width: False
#   flow: True

# mT_etau:
#   x_bins: "auto|0:250"
#   x_title: "m^{T}_{e #tau_{h}} (GeV)"
#   y_title: "Events"
#   use_log_y: False
#   max_y_sf: 1.5
#   divide_by_bin_width: False
#   flow: True

#for Tau FR computation ---------------------------------------------------------------------------------
# Tau_pt:
#   x_bins: "config"
#   x_title: "#tau_{h} p_{T} (GeV)"
#   y_title: "Events"
#   use_log_y: False
#   max_y_sf: 1.5
#   divide_by_bin_width: False
#   flow: True

# Tau_abseta:
#   x_bins: "config"
#   x_title: "#tau_{h} #eta"
#   y_title: "Events"
#   use_log_y: False
#   max_y_sf: 1.5
#   divide_by_bin_width: False
#   flow: False
