#BDT ---------------------------------------------------------------------------------
# tte_eta_sumw:
#   x_bins: "auto|-2:2"
#   x_title: "#frac{1}{3} #Sigma_{i} #eta_{l_i} "
#   y_title: "Events"
#   use_log_y: False
#   max_y_sf: 1.5
#   divide_by_bin_width: False

mT_total_tte:
  x_bins: "auto|50:700"
  x_title: "m^{T}_{total} (GeV)"
  y_title: "Events"
  use_log_y: False
  max_y_sf: 1.5
  divide_by_bin_width: False
  flow: True

mT_tautau:
  x_bins: "auto|0:250"
  x_title: "m^{T}_{#tau_{h} #tau_{h}} (GeV)"
  y_title: "Events"
  use_log_y: False
  max_y_sf: 1.5
  divide_by_bin_width: False
  flow: True

DNNscore:
  x_bins: "auto|0:1"
  x_title: "DNN score for m_{HNL}="
  y_title: "Events"
  use_log_y: False
  max_y_sf: 1.5
  divide_by_bin_width: False
  
# pt_sum_tte:
#   x_bins: "auto|60:400"
#   x_title: "#Sigma_{i}^{#tau_{h} #tau_{h} e} p_{T}^{i} (GeV)"
#   y_title: "Events"
#   use_log_y: False
#   max_y_sf: 1.5
#   divide_by_bin_width: False
#   flow: True

# dr_etau:
#   x_bins: "auto|0:5"
#   x_title: "#Delta R_{e #tau_{h}} (rad)"
#   y_title: "Events"
#   use_log_y: False
#   max_y_sf: 1.5
#   divide_by_bin_width: False
#   flow: True
#---------------------------------------------------------------------------------
# Tau1_pt:
#   x_bins: "6|20:100"
#   x_title: "#tau_{h}^{1} p_{T} (GeV)"
#   y_title: "Events"
#   use_log_y: False
#   max_y_sf: 1.5
#   divide_by_bin_width: False
#   flow: True

# Tau2_pt:
#   x_bins: "6|20:50"
#   x_title: "#tau_{h}^{2} p_{T} (GeV)"
#   y_title: "Events"
#   use_log_y: False
#   max_y_sf: 1.5
#   divide_by_bin_width: False
#   flow: True

# Electron_pt:
#   x_bins: "6|30:130"
#   x_title: "e p_{T} (GeV)"
#   y_title: "Events"
#   use_log_y: False
#   max_y_sf: 1.5
#   divide_by_bin_width: False
#   flow: True