Electron_ptcorr:
  x_bins: "config" #[10.0, 12.392091178894043, 15.374319076538086, 21.135328292846687, 37.12989349365235, 100.0]
  x_title: "e p_{T}^{corr} (GeV)"
  y_title: "Events"
  use_log_y: False
  max_y_sf: 1.5
  divide_by_bin_width: False
  flow: True

Electron_abseta:
  x_bins: "config" #[0.0, 0.543212890625, 1.033935546875, 1.5782226562500004, 2.00078125, 2.5]
  x_title: "e |#eta|"
  y_title: "Events"
  use_log_y: False
  max_y_sf: 1.5
  divide_by_bin_width: False
  flow: False
