Tau:
  pt: [0, 25, 30, 35, 45, 1000]
  abseta: [0, 0.3, 0.6, 1.0, 1.5, 2.5]

Electron:
  pt: [0, 13, 17, 23, 45, 1000]
  abseta: [0, 0.5, 1.0, 1.5, 2.0, 2.5]

Muon:
  pt: [0, 20, 25, 30, 50, 1000]
  abseta: [0, 0.4, 0.8, 1.3, 1.8, 2.5]