name: PlotKit
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _sysroot_linux-64_curr_repodata_hack=3=h5bd9786_13
  - afterimage=1.21=ha9998ff_1003
  - anyio=3.6.2=pyhd8ed1ab_0
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py39hb9d737c_3
  - asttokens=2.2.1=pyhd8ed1ab_0
  - atk-1.0=2.38.0=hd4edc92_1
  - attrs=22.2.0=pyh71513ae_0
  - awkward=2.0.8=pyhd8ed1ab_0
  - awkward-cpp=9=py39h4b4f3f3_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - beautifulsoup4=4.11.2=pyha770c72_0
  - binutils=2.39=hdd6e379_1
  - binutils_impl_linux-64=2.39=he00db2b_1
  - binutils_linux-64=2.39=h5fc0e48_11
  - bleach=6.0.0=pyhd8ed1ab_0
  - boost=1.80.0=py39h7c9e3ff_4
  - boost-cpp=1.80.0=h75c5d50_0
  - boost-histogram=1.3.2=py39hf939315_2
  - brotli=1.0.9=h166bdaf_8
  - brotli-bin=1.0.9=h166bdaf_8
  - brotlipy=0.7.0=py39hb9d737c_1005
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - c-compiler=1.5.1=h166bdaf_0
  - ca-certificates=2023.7.22=hbcca054_0
  - cairo=1.16.0=ha61ee94_1014
  - certifi=2023.7.22=pyhd8ed1ab_0
  - cffi=1.15.1=py39he91dace_3
  - cfitsio=4.1.0=hd9d235c_0
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - click=8.1.3=unix_pyhd8ed1ab_2
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.1.2=pyhd8ed1ab_0
  - compilers=1.5.1=ha770c72_0
  - contourpy=1.0.7=py39h4b4f3f3_0
  - correctionlib=2.3.3=py39h7633fee_1
  - cryptography=39.0.1=py39h079d5ae_0
  - cxx-compiler=1.5.1=h924138e_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - davix=0.8.4=h238e42b_0
  - debugpy=1.6.6=py39h227be39_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - docutils=0.20.1=py39hf3d152e_2
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - expat=2.5.0=h27087fc_0
  - fftw=3.3.10=nompi_hf0379b8_106
  - flit-core=3.8.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.38.0=py39hb9d737c_1
  - fortran-compiler=1.5.1=h2a4ca65_0
  - freetype=2.12.1=hca18f0e_1
  - fribidi=1.0.10=h36c2ea0_0
  - ftgl=2.4.0=hbcb1f35_0
  - gcc=10.4.0=hb92f740_11
  - gcc_impl_linux-64=10.4.0=h5231bdf_19
  - gcc_linux-64=10.4.0=h9215b83_11
  - gdk-pixbuf=2.42.8=hff1cb4f_1
  - gettext=0.21.1=h27087fc_0
  - gfortran=10.4.0=h0c96582_11
  - gfortran_impl_linux-64=10.4.0=h7d168d2_19
  - gfortran_linux-64=10.4.0=h69d5af5_11
  - giflib=5.2.1=h36c2ea0_2
  - gl2ps=1.4.2=h0708190_0
  - glew=2.1.0=h9c3ff4c_2
  - graphite2=1.3.13=h58526e2_1001
  - graphviz=6.0.2=h99bc08f_0
  - gsl=2.7=he838d99_0
  - gsoap=2.8.123=h8dc497d_0
  - gtk2=2.24.33=h90689f9_2
  - gts=0.7.6=h64030ff_2
  - gxx=10.4.0=hb92f740_11
  - gxx_impl_linux-64=10.4.0=h5231bdf_19
  - gxx_linux-64=10.4.0=h6e491c6_11
  - harfbuzz=6.0.0=h8e241bc_0
  - hist=2.6.3=pyhd8ed1ab_0
  - histoprint=2.4.0=pyhd8ed1ab_0
  - icu=70.1=h27087fc_0
  - idna=3.4=pyhd8ed1ab_0
  - iminuit=2.20.0=py39h227be39_0
  - importlib-metadata=6.0.0=pyha770c72_0
  - importlib-resources=5.12.0=pyhd8ed1ab_0
  - importlib_metadata=6.0.0=hd8ed1ab_0
  - importlib_resources=5.12.0=pyhd8ed1ab_0
  - ipykernel=6.21.2=pyh210e3f2_0
  - ipyparallel=8.4.1=pyhd8ed1ab_0
  - ipython=8.11.0=pyh41d4057_0
  - ipython_genutils=0.2.0=py_1
  - jedi=0.18.2=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - jpeg=9e=h0b41bf4_3
  - jsonschema=4.17.3=pyhd8ed1ab_0
  - jupyter_client=8.0.3=pyhd8ed1ab_0
  - jupyter_core=5.2.0=py39hf3d152e_0
  - jupyter_events=0.6.3=pyhd8ed1ab_0
  - jupyter_server=2.3.0=pyhd8ed1ab_0
  - jupyter_server_terminals=0.4.4=pyhd8ed1ab_1
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - kernel-headers_linux-64=3.10.0=h4a8ded7_13
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.4=py39hf939315_1
  - krb5=1.20.1=h81ceb04_0
  - law=0.1.14=pyhca7485f_0
  - lcms2=2.14=h6ed2654_0
  - ld_impl_linux-64=2.39=hcc3a1bd_1
  - lerc=4.0.0=h27087fc_0
  - libblas=3.9.0=16_linux64_openblas
  - libbrotlicommon=1.0.9=h166bdaf_8
  - libbrotlidec=1.0.9=h166bdaf_8
  - libbrotlienc=1.0.9=h166bdaf_8
  - libcblas=3.9.0=16_linux64_openblas
  - libcurl=7.88.1=hdc1c0ab_0
  - libcxx=14.0.6=hf52228f_0
  - libcxxabi=14.0.6=ha770c72_0
  - libdeflate=1.14=h166bdaf_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libffi=3.4.2=h7f98852_5
  - libgcc-devel_linux-64=10.4.0=hd38fd1e_19
  - libgcc-ng=12.2.0=h65d4601_19
  - libgd=2.3.3=h18fbbfe_3
  - libgfortran-ng=12.2.0=h69a702a_19
  - libgfortran5=12.2.0=h337968e_19
  - libglib=2.74.1=h606061b_1
  - libglu=9.0.0=he1b5a44_1001
  - libgomp=12.2.0=h65d4601_19
  - libhwloc=2.9.0=hd6dc26d_0
  - libiconv=1.17=h166bdaf_0
  - liblapack=3.9.0=16_linux64_openblas
  - libllvm11=11.1.0=he0ac6c6_5
  - libllvm9=9.0.1=default_hc23dcda_7
  - libnghttp2=1.52.0=h61bc06f_0
  - libnsl=2.0.0=h7f98852_0
  - libopenblas=0.3.21=pthreads_h78a6416_3
  - libpng=1.6.39=h753d276_0
  - librsvg=2.54.4=h7abd40a_0
  - libsanitizer=10.4.0=h5246dfb_19
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.40.0=h753d276_0
  - libssh2=1.10.0=hf14f497_3
  - libstdcxx-devel_linux-64=10.4.0=hd38fd1e_19
  - libstdcxx-ng=12.2.0=h46fd767_19
  - libtiff=4.4.0=h82bc61c_5
  - libtool=2.4.7=h27087fc_0
  - libuuid=2.32.1=h7f98852_1000
  - libwebp=1.2.4=h522a892_0
  - libwebp-base=1.2.4=h166bdaf_0
  - libxcb=1.13=h7f98852_1004
  - libxml2=2.10.3=h7463322_0
  - libzlib=1.2.13=h166bdaf_4
  - llvmlite=0.39.1=py39h7d9a04d_1
  - lockfile=0.12.2=py_1
  - luigi=3.4.0=py39hf3d152e_0
  - lz4=4.3.2=py39h724f13c_0
  - lz4-c=1.9.4=hcb278e6_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_0
  - markupsafe=2.1.2=py39h72bdee0_0
  - matplotlib-base=3.7.0=py39he190548_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mdurl=0.1.0=pyhd8ed1ab_0
  - metakernel=0.29.4=pyhd8ed1ab_0
  - mistune=2.0.5=pyhd8ed1ab_0
  - mplhep=0.3.26=pyhd8ed1ab_0
  - mplhep_data=0.0.3=pyhd8ed1ab_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - nbclassic=0.5.2=pyhd8ed1ab_0
  - nbclient=0.7.2=pyhd8ed1ab_0
  - nbconvert=7.2.9=pyhd8ed1ab_0
  - nbconvert-core=7.2.9=pyhd8ed1ab_0
  - nbconvert-pandoc=7.2.9=pyhd8ed1ab_0
  - nbformat=5.7.3=pyhd8ed1ab_0
  - ncurses=6.3=h27087fc_1
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - nlohmann_json=3.11.2=h27087fc_0
  - notebook=6.5.2=pyha770c72_1
  - notebook-shim=0.2.2=pyhd8ed1ab_0
  - numba=0.56.4=py39h61ddf18_0
  - numpy=1.23.5=py39h3d75532_0
  - openjpeg=2.5.0=h7d73246_1
  - openssl=3.1.4=hd590300_0
  - packaging=23.0=pyhd8ed1ab_0
  - pandoc=2.19.2=h32600fe_1
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - pango=1.50.13=hd33c08f_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pcre=8.45=h9c3ff4c_0
  - pcre2=10.40=hc3806b6_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.2.0=py39hf3a2cdf_3
  - pip=23.0.1=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - platformdirs=3.0.0=pyhd8ed1ab_0
  - pooch=1.7.0=pyhd8ed1ab_0
  - portalocker=2.7.0=py39hf3d152e_0
  - prometheus_client=0.13.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.38=pyha770c72_0
  - prompt_toolkit=3.0.38=hd8ed1ab_0
  - psutil=5.9.4=py39hb9d737c_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pydantic=1.10.13=py39hd1e30aa_1
  - pygments=2.14.0=pyhd8ed1ab_0
  - pyopenssl=23.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyrsistent=0.19.3=py39h72bdee0_0
  - pysocks=1.7.1=pyha2e5f31_6
  - pythia8=8.307=py39h5a03fae_0
  - python=3.9.16=h2782a2a_0_cpython
  - python-daemon=3.0.1=pyhd8ed1ab_1
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.16.3=pyhd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-xxhash=3.0.0=py39hb9d737c_2
  - python_abi=3.9=3_cp39
  - pyyaml=6.0=py39hb9d737c_5
  - pyzmq=25.0.0=py39h0be026e_0
  - readline=8.1.2=h0f457ee_0
  - requests=2.28.2=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rich=13.6.0=pyhd8ed1ab_0
  - root=6.26.10=py39h4661b88_1
  - root_base=6.26.10=py39h7695a35_1
  - scipy=1.10.1=py39h7360e5f_0
  - scitokens-cpp=0.7.1=hf3971a6_0
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=67.4.0=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - sniffio=1.3.0=pyhd8ed1ab_0
  - soupsieve=2.3.2.post1=pyhd8ed1ab_0
  - sqlite=3.40.0=h4ff8645_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - sysroot_linux-64=2.17=h4a8ded7_13
  - tbb=2021.8.0=hf52228f_0
  - tenacity=8.2.3=pyhd8ed1ab_0
  - terminado=0.17.1=pyh41d4057_0
  - tinycss2=1.2.1=pyhd8ed1ab_0
  - tk=8.6.12=h27826a3_0
  - toml=0.10.2=pyhd8ed1ab_0
  - tornado=6.2=py39hb9d737c_1
  - tqdm=4.64.1=pyhd8ed1ab_0
  - traitlets=5.9.0=pyhd8ed1ab_0
  - typing-extensions=4.4.0=hd8ed1ab_0
  - typing_extensions=4.4.0=pyha770c72_0
  - tzdata=2022g=h191b570_0
  - uhi=0.3.3=pyhd8ed1ab_0
  - unicodedata2=15.0.0=py39hb9d737c_0
  - uproot=5.0.4=ha770c72_0
  - uproot-base=5.0.4=pyhd8ed1ab_0
  - urllib3=1.26.14=pyhd8ed1ab_0
  - vdt=0.4.3=h9c3ff4c_0
  - vector-classes=1.4.3=h924138e_0
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - webencodings=0.5.1=py_1
  - websocket-client=1.5.1=pyhd8ed1ab_0
  - wheel=0.38.4=pyhd8ed1ab_0
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.6.12=h36c2ea0_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxcursor=1.2.0=h516909a_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxfixes=5.0.3=h516909a_1004
  - xorg-libxft=2.3.4=hc534e41_1
  - xorg-libxpm=3.5.13=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-libxt=1.1.5=h516909a_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h7f98852_1007
  - xrootd=5.5.3=py39hc80556b_0
  - xxhash=0.8.0=h7f98852_3
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - zeromq=4.3.4=h9c3ff4c_1
  - zipp=3.15.0=pyhd8ed1ab_0
  - zlib=1.2.13=h166bdaf_4
  - zstandard=0.19.0=py39h29414ee_1
  - zstd=1.5.2=h3eb15da_6
prefix: /afs/cern.ch/work/p/pdebryas/miniconda3/envs/PlotKit
