name: MLenv
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _x86_64-microarch-level=1=2_x86_64
  - awkward=2.7.4=pyhd8ed1ab_0
  - awkward-cpp=44=py39hd3a5d65_100
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2025.4.26=hbd8a1cb_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - cpython=3.9.21=py39hd8ed1ab_1
  - cramjam=2.8.4rc3=py39he1787b6_2
  - filelock=3.17.0=pyhd8ed1ab_0
  - fsspec=2025.2.0=pyhd8ed1ab_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.1.5=py39h7196dd7_3
  - importlib-metadata=8.6.1=pyha770c72_0
  - jinja2=3.1.5=pyhd8ed1ab_0
  - joblib=1.4.2=pyhd8ed1ab_1
  - ld_impl_linux-64=2.43=h712a8e2_4
  - libabseil=20240722.0=cxx17_hbbce691_4
  - libblas=3.9.0=31_h59b9bed_openblas
  - libcblas=3.9.0=31_he106b2a_openblas
  - libffi=3.4.6=h2dba641_0
  - libgcc=14.2.0=h767d61c_2
  - libgcc-ng=14.2.0=h69a702a_2
  - libgfortran=14.2.0=h69a702a_2
  - libgfortran-ng=14.2.0=h69a702a_2
  - libgfortran5=14.2.0=hf1ad2bd_2
  - libgomp=14.2.0=h767d61c_2
  - liblapack=3.9.0=31_h7ac8fdf_openblas
  - liblzma=5.6.4=hb9d3cd8_0
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.29=pthreads_h94d23a6_0
  - libprotobuf=5.28.3=h6128344_1
  - libsqlite=3.49.1=hee588c1_1
  - libstdcxx=14.2.0=h8f9b012_2
  - libstdcxx-ng=14.2.0=h4852527_2
  - libtorch=2.6.0=cpu_generic_haed06de_0
  - libuuid=2.38.1=h0b41bf4_0
  - libuv=1.50.0=hb9d3cd8_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - markupsafe=3.0.2=py39h9399b63_1
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - networkx=3.2.1=pyhd8ed1ab_0
  - nomkl=1.0=h5ca1d4c_0
  - numpy=2.0.2=py39h9cb892a_1
  - openssl=3.5.0=h7b32b05_1
  - optree=0.14.1=py39h74842e3_0
  - packaging=24.2=pyhd8ed1ab_2
  - pandas=2.2.3=py39h3b40f6f_2
  - pip=25.0.1=pyh8b19718_0
  - pybind11=2.13.6=pyh1ec8472_2
  - pybind11-global=2.13.6=pyh415d2e4_2
  - python=3.9.21=h9c0c6dc_1_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-tzdata=2025.1=pyhd8ed1ab_0
  - python-xxhash=3.5.0=py39h8cd3c5a_2
  - python_abi=3.9=5_cp39
  - pytorch=2.6.0=cpu_generic_py39_h57ffae5_0
  - pytz=2024.1=pyhd8ed1ab_0
  - pyyaml=6.0.2=py39h9399b63_2
  - readline=8.2=h8c095d6_2
  - scikit-learn=1.6.1=py39h4b7350c_0
  - scipy=1.13.1=py39haf93ffa_0
  - setuptools=75.8.2=pyhff2d567_0
  - six=1.17.0=pyhd8ed1ab_0
  - sleef=3.8=h1b44611_0
  - sympy=1.13.3=pyh2585a3b_105
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tk=8.6.13=noxft_h4845f30_101
  - tqdm=4.67.1=pyhd8ed1ab_1
  - typing-extensions=4.12.2=hd8ed1ab_1
  - typing_extensions=4.12.2=pyha770c72_1
  - tzdata=2025a=h78e105d_0
  - uproot=5.5.2=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - xxhash=0.8.3=hb9d3cd8_0
  - yaml=0.2.5=h7f98852_2
  - zipp=3.21.0=pyhd8ed1ab_1
  - pip:
    - vector==1.6.1
prefix: /afs/cern.ch/work/p/pdebryas/miniconda3/envs/MLenv
