- name: HNL
  files:
  - HNL_tau_M-20_anatuple.root 
  - HNL_tau_M-30_anatuple.root 
  - HNL_tau_M-40_anatuple.root 
  - HNL_tau_M-50_anatuple.root 
  - HNL_tau_M-60_anatuple.root 
  - HNL_tau_M-70_anatuple.root 
  - HNL_tau_M-75_anatuple.root 
  - HNL_tau_M-85_anatuple.root 
  - HNL_tau_M-100_anatuple.root 
  - HNL_tau_M-125_anatuple.root 
  - HNL_tau_M-150_anatuple.root 
  - HNL_tau_M-200_anatuple.root 
  - HNL_tau_M-250_anatuple.root 
  - HNL_tau_M-300_anatuple.root 
  - HNL_tau_M-350_anatuple.root 
  - HNL_tau_M-400_anatuple.root 
  - HNL_tau_M-450_anatuple.root
  - HNL_tau_M-500_anatuple.root 
  - HNL_tau_M-600_anatuple.root 
  - HNL_tau_M-700_anatuple.root
  - HNL_tau_M-800_anatuple.root 
  - HNL_tau_M-900_anatuple.root 
  - HNL_tau_M-1000_anatuple.root 
  # - HNL_VBF_tau_M-600_anatuple.root   
  # - HNL_VBF_tau_M-700_anatuple.root  
  # - HNL_VBF_tau_M-800_anatuple.root  
  # - HNL_VBF_tau_M-900_anatuple.root  
  # - HNL_VBF_tau_M-1000_anatuple.root  